// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLuYF2OfsXYs0sCSvvtsoAX_-X_n7PShQ',
    appId: '1:272030031183:web:327c87c3fe43d86f3d393a',
    messagingSenderId: '272030031183',
    projectId: 'zoom-clone-819f8',
    authDomain: 'zoom-clone-819f8.firebaseapp.com',
    storageBucket: 'zoom-clone-819f8.appspot.com',
    measurementId: 'G-HQDQ0G7J1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI7KN7PZoGsNVFlX2zz2zwN9Ay-4QkGMY',
    appId: '1:272030031183:android:a7654ba7db63d7223d393a',
    messagingSenderId: '272030031183',
    projectId: 'zoom-clone-819f8',
    storageBucket: 'zoom-clone-819f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPBc2hoFCbs9uZblr5xVvUowZ-wsBLhhA',
    appId: '1:272030031183:ios:ba10cb0274b9fd543d393a',
    messagingSenderId: '272030031183',
    projectId: 'zoom-clone-819f8',
    storageBucket: 'zoom-clone-819f8.appspot.com',
    iosClientId: '272030031183-9tkuf1usctr4v3tcdngocujrfdlkr22i.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPBc2hoFCbs9uZblr5xVvUowZ-wsBLhhA',
    appId: '1:272030031183:ios:ba10cb0274b9fd543d393a',
    messagingSenderId: '272030031183',
    projectId: 'zoom-clone-819f8',
    storageBucket: 'zoom-clone-819f8.appspot.com',
    iosClientId: '272030031183-9tkuf1usctr4v3tcdngocujrfdlkr22i.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLuYF2OfsXYs0sCSvvtsoAX_-X_n7PShQ',
    appId: '1:272030031183:web:a4622eb8748c4d233d393a',
    messagingSenderId: '272030031183',
    projectId: 'zoom-clone-819f8',
    authDomain: 'zoom-clone-819f8.firebaseapp.com',
    storageBucket: 'zoom-clone-819f8.appspot.com',
    measurementId: 'G-75FJT0QYD4',
  );
}
